language: python
branches:
 only:
   - main
python:
  - '3.9'
  - '3.10'
  - '3.11'
install:
  - pip install setuptools --upgrade
  - python setup.py install
script:
  - flask_s3_viewer -h
notifications:
  email: d.hidekuma@gmail.com
